# Version: 1.0.6
# ✅ working
# Appartement: Romains
blueprint:
  name: "💡 Extinction Auto Lumières (Présence Temporisée)"
  description: >
    Version: 1.0.6
    Extinction automatique des lumières basée sur un capteur de présence temporisée.
    Simple et efficace : le capteur gère déjà la temporisation.
  domain: automation
  # ==============================================================================
  # INPUTS - Configuration des paramètres du blueprint
  # ==============================================================================
  input:
    # --------------------------------------------------------------------------
    # Capteur de présence temporisée : détection avec délai intégré
    # Type attendu : binary_sensor.xxx (avec temporisation intégrée)
    # Valeur attendue : on = présence détectée, off = absence prolongée
    # --------------------------------------------------------------------------
    presence_sensor:
      name: 🕵️ Capteur de présence temporisée
      description: Le capteur binaire qui détecte la présence (avec temporisation intégrée)
      default: binary_sensor.presence_communs_temporisee
      selector:
        entity:
          domain: binary_sensor

    # --------------------------------------------------------------------------
    # Lumières à contrôler : interrupteurs switch
    # Type attendu : switch.xxx (interrupteurs/télérupteurs)
    # Valeur attendue : on = allumé, off = éteint
    # --------------------------------------------------------------------------
    light_switches:
      name: 💡 Lumières à éteindre
      description: Sélectionnez les interrupteurs de lumières à contrôler
      default:
        - switch.telerupteur_romains_lumieres_cuisine
        - switch.telerupteur_romains_lumieres_salon
      selector:
        entity:
          domain: switch
          multiple: true

    # --------------------------------------------------------------------------
    # Tracker d'événements : suivi du déroulement de l'automation
    # Type attendu : input_select.xxx (Helper > Dropdown)
    # Valeur attendue : Options comme run, aborted_presence, lights_off
    # Créer via UI : Settings > Helpers > Create Helper > Dropdown
    # --------------------------------------------------------------------------
    automation_events_tracker:
      name: 🧾 Tracker d'événements d'automation
      description: Input select pour suivre les événements de l'automation
      default: input_select.lights_automation_events
      selector:
        entity:
          domain: input_select

    # --------------------------------------------------------------------------
    # Délai de grâce : temps d'attente après allumage manuel
    # Type attendu : input_number.xxx (Helper > Number)
    # Valeur attendue : durée en secondes (recommandé : >= 40)
    # Créer via UI : Settings > Helpers > Create Helper > Number
    # --------------------------------------------------------------------------
    grace_period_on_light_on:
      name: ⏱️ Délai de grâce après allumage
      description: >
        Entité input_number définissant le temps d'attente avant extinction si lumière allumée alors que pas de présence.
        Recommandé : au moins 40 secondes. En dessous, uniquement pour les tests.
      default: input_number.duree_grace_period_on_light_on
      selector:
        entity:
          domain: input_number

    # --------------------------------------------------------------------------
    # Compteur d'extinctions : statistiques d'utilisation
    # Type attendu : counter.xxx (Helper > Counter)
    # Valeur attendue : nombre entier incrémental
    # Créer via UI : Settings > Helpers > Create Helper > Counter
    # --------------------------------------------------------------------------
    auto_off_counter:
      name: 🔢 Compteur d'extinctions automatiques
      description: Entité counter qui compte le nombre de fois où l'automation a éteint les lumières
      default: counter.salon_lights_auto_off_count
      selector:
        entity:
          domain: counter

# ==============================================================================
# MODE RESTART : Redémarre l'automation si elle se déclenche pendant son exécution
# ==============================================================================
mode: restart
max_exceeded: silent

# ==============================================================================
# TRIGGERS : Événements qui déclenchent l'automation
# ==============================================================================
trigger:
  # --------------------------------------------------------------------------
  # Trigger 1 : Détection d'absence
  # Se déclenche quand : le capteur de présence passe à off
  # Objectif : lancer l'extinction des lumières après temporisation
  # --------------------------------------------------------------------------
  - platform: state
    entity_id: !input presence_sensor
    to: "off"
    id: presence_off

  # --------------------------------------------------------------------------
  # Trigger 2 : Allumage manuel pendant absence
  # Se déclenche quand : une lumière est allumée alors qu'il n'y a pas de présence
  # Objectif : éteindre automatiquement après un délai de grâce
  # --------------------------------------------------------------------------
  - platform: state
    entity_id: !input light_switches
    to: "on"
    id: light_turned_on

# ==============================================================================
# CONDITION : Vérifications avant exécution
# ==============================================================================
condition:
  # Vérifie qu'au moins une lumière est allumée avant d'agir
  # (évite de lancer l'automation inutilement)
  - condition: template
    value_template: >
      {% set switches = light_switches %}
      {{ switches | select('is_state', 'on') | list | count > 0 }}

# ==============================================================================
# VARIABLES : Préparation des données pour l'action
# ==============================================================================
variables:
  light_switches: !input light_switches
  grace_period_entity: !input grace_period_on_light_on

# ==============================================================================
# ACTION : Séquence d'extinction intelligente des lumières
# ==============================================================================
action:
  # État : démarrage
  - service: input_select.select_option
    target:
      entity_id: !input automation_events_tracker
    data:
      option: run

  # Si trigger = light_turned_on, vérifier que présence = OFF
  - choose:
      - conditions:
          - condition: trigger
            id: light_turned_on
          - condition: state
            entity_id: !input presence_sensor
            state: "on"
        sequence:
          - service: input_select.select_option
            target:
              entity_id: !input automation_events_tracker
            data:
              option: aborted_presence
          - delay:
              seconds: 20
          - service: input_select.select_option
            target:
              entity_id: !input automation_events_tracker
            data:
              option: idle
          - stop: Lumière allumée mais présence détectée

  # Délai de grâce si allumage manuel (trigger light_turned_on)
  - choose:
      - conditions:
          - condition: trigger
            id: light_turned_on
        sequence:
          - delay:
              seconds: "{{ states(grace_period_entity) | int }}"

  # Double vérification de la présence (sécurité)
  - choose:
      - conditions:
          - condition: state
            entity_id: !input presence_sensor
            state: "on"
        sequence:
          - service: input_select.select_option
            target:
              entity_id: !input automation_events_tracker
            data:
              option: aborted_presence
          - delay:
              seconds: 20
          - service: input_select.select_option
            target:
              entity_id: !input automation_events_tracker
            data:
              option: idle
          - stop: Présence détectée – extinction annulée

  # Extinction des lumières
  - service: switch.turn_off
    target:
      entity_id: !input light_switches

  # Incrémentation du compteur
  - service: counter.increment
    target:
      entity_id: !input auto_off_counter

  # État : lumières éteintes
  - service: input_select.select_option
    target:
      entity_id: !input automation_events_tracker
    data:
      option: lights_off

  # Log de l'événement
  - service: system_log.write
    data:
      level: info
      message: >
        Extinction auto validée : absence confirmée via capteur de présence temporisée.
        Lumières éteintes : {{ light_switches | join(', ') }}

  # Attente avant retour à l'état idle
  - delay:
      seconds: 20

  # État : terminé avec succès
  - service: input_select.select_option
    target:
      entity_id: !input automation_events_tracker
    data:
      option: idle
