alias: "🔊 Denon : rotation mode audio (stereo / all zone / dolby)"
description: >
  Webhook pour faire tourner le mode audio du Denon :
  stereo -> all zone stereo -> dolby -> stereo (etc).
  Se base sur les libellés réellement disponibles dans `sound_mode_list`.

trigger:
  # --------------------------------------------------------------------------
  # Déclencheur : appel webhook local
  # Méthode : POST
  # URL (exemple) : /api/webhook/toggle-sound-mode
  # --------------------------------------------------------------------------
  - platform: webhook
    allowed_methods:
      - POST
    local_only: true
    webhook_id: toggle-sound-mode

condition: []

action:
  # --------------------------------------------------------------------------
  # Variables de base
  # - denon_entity : media_player Denon (intégration officielle)
  # - current_mode : mode audio courant (attribut `sound_mode`)
  # - available_modes : liste des modes audio disponibles (attribut `sound_mode_list`)
  # --------------------------------------------------------------------------
  - variables:
      denon_entity: media_player.denon_avr_x2800h
      current_mode: "{{ state_attr(denon_entity, 'sound_mode') | default('') | string }}"
      available_modes: "{{ state_attr(denon_entity, 'sound_mode_list') or [] }}"

      # ----------------------------------------------------------------------
      # Détection des libellés "cibles" dans `sound_mode_list`
      # Important : on ne force pas un texte fixe, on choisit le libellé EXACT
      # présent dans la liste (selon modèle / firmware / langue du Denon).
      # ----------------------------------------------------------------------
      stereo_option: >-
        {% set opts = available_modes %}
        {% set ns = namespace(match='') %}
        {% for o in opts %}
          {% set lo = (o | string | lower) %}
          {% if lo == 'stereo' %}
            {% set ns.match = o %}
            {% break %}
          {% endif %}
        {% endfor %}
        {% if ns.match == '' %}
          {% for o in opts %}
            {% set lo = (o | string | lower) %}
            {% if ('stereo' in lo) and not (('all' in lo) and ('zone' in lo)) %}
              {% set ns.match = o %}
              {% break %}
            {% endif %}
          {% endfor %}
        {% endif %}
        {{ ns.match }}

      all_zone_stereo_option: >-
        {% set opts = available_modes %}
        {% set ns = namespace(match='') %}
        {% for o in opts %}
          {% set lo = (o | string | lower) %}
          {% if ('all' in lo) and ('zone' in lo) and ('stereo' in lo) %}
            {% set ns.match = o %}
            {% break %}
          {% endif %}
        {% endfor %}
        {{ ns.match }}

      dolby_option: >-
        {% set opts = available_modes %}
        {% set ns = namespace(match='') %}
        {% for o in opts %}
          {% set lo = (o | string | lower) %}
          {% if 'dolby' in lo %}
            {% set ns.match = o %}
            {% break %}
          {% endif %}
        {% endfor %}
        {{ ns.match }}

      # ----------------------------------------------------------------------
      # Normalisation du mode courant + flags d'état
      # - is_stereo : "stereo" mais pas "all zone stereo"
      # - is_all_zone : contient all + zone + stereo
      # - is_dolby : contient dolby
      # ----------------------------------------------------------------------
      current_norm: "{{ current_mode | lower }}"
      is_stereo: "{{ ('stereo' in current_norm) and not (('all' in current_norm) and ('zone' in current_norm)) }}"
      is_all_zone: "{{ ('all' in current_norm) and ('zone' in current_norm) and ('stereo' in current_norm) }}"
      is_dolby: "{{ 'dolby' in current_norm }}"

      # ----------------------------------------------------------------------
      # Rotation demandée : stereo -> all zone stereo -> dolby -> stereo
      # Fallbacks :
      # - si un mode n'existe pas dans sound_mode_list, on saute au suivant
      # - si mode courant inconnu : on tente stereo, sinon premier élément de la liste
      # ----------------------------------------------------------------------
      next_mode: >-
        {% if is_stereo %}
          {{ all_zone_stereo_option if (all_zone_stereo_option | length > 0) else (dolby_option if (dolby_option | length > 0) else stereo_option) }}
        {% elif is_all_zone %}
          {{ dolby_option if (dolby_option | length > 0) else stereo_option }}
        {% elif is_dolby %}
          {{ stereo_option if (stereo_option | length > 0) else all_zone_stereo_option }}
        {% else %}
          {{ stereo_option if (stereo_option | length > 0) else (available_modes[0] if (available_modes | length > 0) else '') }}
        {% endif %}

  - choose:
      # ----------------------------------------------------------------------
      # Application du mode suivant si calculé
      # ----------------------------------------------------------------------
      - conditions:
          - condition: template
            value_template: "{{ next_mode | length > 0 }}"
        sequence:
          - service: media_player.select_sound_mode
            target:
              entity_id: "{{ denon_entity }}"
            data:
              sound_mode: "{{ next_mode }}"

mode: single
